### ISSUE TITLE
Sing up page does not open

### ISSUE THREAD

**Issue by ihossein79** [ihossein79/Developer#1]
When the sing-up page is clicked, the sing-up page does not open

**Comment by sajadbz** [comment]
Register page is ok and then clicking on it, it open.
Register page issue is .cshtml and HTML tags in it, you must remove HTML tag and another extra thing:

![image](https://user-images.githubusercontent.com/57556662/142981257-7f2ad86b-6ff9-4359-a33b-1b5eb3fb34b9.png)

-- The register page doesn't have a Model.

**Comment by sajadbz** [comment]
@ihossein79  Check this PR #2 
[PR #2 files](https://github.com/ihossein79/Developer/pull/2/files)
